---
title: "Test sites"
author: "Lucas Moitinho-Silva"
date: "`r Sys.Date()`"
output:
   BiocStyle::html_document:
      toc: true
      df_print: paged
      self_contained: true
      code_download: true
      highlight: tango
#bibliography: mylib.bib
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
  d.out: "./"
---


# Introduction


# Preparations

## Set global options

```{r style, echo = T, results="asis", cache=FALSE, message = F}
# Set knit global options
library("knitr")
options(digits = 2, width = 80)
golden_ratio <- (1 + sqrt(5)) / 2
opts_chunk$set(echo = TRUE,
               tidy = FALSE,
               include = TRUE,
               fig.path = params$FIGPATH,
               dev=c("png",'pdf'),
               fig.height = 5,
               fig.width = 4 * golden_ratio,
               comment = '  ',
               dpi = 300,
               cache = FALSE)
library("rmarkdown")

# Pretty outputs
library("BiocStyle")
library("ggthemes") # add ggplot2 themes
library("ggplot2")
theme_set(theme_few(base_size = 14))

# Set seed for reproducibility
#set.seed(13)

# Set output directory
d.out <- params$d.out
index <- params$index
rm(params)
```


## Load libraries for the session

```{r}
library(tidyverse)
library(ggplot2)
library(vegan)
library(foreach)
library(doParallel)
library(formula.tools)
```

## Import data
```{r}
# Input folders
d.in.diversity <- "~/IKMB/projects/skin.associations/results/popgen/2.host.trait.set/2.get.diversity"

micro.r <- bind_rows(paste0("i1.micro.rarefied.rds") %>% 
                       paste0(d.in.diversity, "/", .) %>% 
                       readRDS() %>% 
                       rownames_to_column("NGS_ID"),
                     paste0("i2.micro.rarefied.rds") %>% 
                       paste0(d.in.diversity, "/", .) %>% 
                       readRDS() %>% 
                       rownames_to_column("NGS_ID"),
                     paste0("i3.micro.rarefied.rds") %>% 
                       paste0(d.in.diversity, "/", .) %>% 
                       readRDS() %>% 
                       rownames_to_column("NGS_ID"),
                     paste0("i4.micro.rarefied.rds") %>% 
                       paste0(d.in.diversity, "/", .) %>% 
                       readRDS() %>% 
                       rownames_to_column("NGS_ID"))
micro.r[is.na(micro.r)] <- 0


pheno <- bind_rows(paste0("i1.pheno.rds") %>% 
                     paste0(d.in.diversity, "/", .) %>% 
                     readRDS() %>% 
                     mutate(Site = "Antecubital fossa"),
                   paste0("i2.pheno.rds") %>% 
                     paste0(d.in.diversity, "/", .) %>% 
                     readRDS() %>% 
                     mutate(Site = "Volar forearm"),
                   paste0("i3.pheno.rds") %>% 
                     paste0(d.in.diversity, "/", .) %>% 
                     readRDS() %>% 
                     mutate(Site = "Dorsal forearm"),
                   paste0("i4.pheno.rds") %>% 
                     paste0(d.in.diversity, "/", .) %>% 
                     readRDS() %>% 
                     mutate(Site = "Forehead"))

identical(micro.r$NGS_ID, pheno$NGS_ID)

microenv <- "~/IKMB/projects/skin.associations/scripts/data.dic/skin.microenv.tsv" %>% 
  read_tsv()
```

```{r}
pheno <- pheno %>% 
  left_join(microenv, by = "Site")
```

# Function

```{r}
#Adonis2 routine
adonis.routine <- function(f){
  res <- adonis2(f, data = pheno.test, permutations = 999, by = "terms", parallel = nc) %>%
    data.frame() %>% 
    rownames_to_column("x") %>% 
    rename("p.value" =  "Pr..F.") %>% 
    rename("term" = "x")  %>% 
    filter(term == i) 
  return(res)}
```


#Test variables on betadiversity.


```{r}

# Parameters of the test

controls <- c("t14110_gender", "t4_examination_age", "t277_BMI","wash", "cream")

# Set significance----

q  <- 0.05

# Set cpus ---
nc <- 7

n.rep <- 100
res <- NULL

i <- "Microenvironment"
for (i in c("Site", "Microenvironment")){
  for (n.round in 1:n.rep){
    
    set.seed(n.round)  
    
    # get random set of samples. One site per participant.
    
    n <- pheno %>% pull(Participant_ID) %>% unique() %>% length()
    
    names <- pheno %>% pull(get(i)) %>% unique()
    
    samples <- data.frame(Participant_ID = pheno %>% 
                            pull(Participant_ID) %>% 
                            unique() %>% 
                            sample,
                          names = rep(names, 
                                      n) %>% 
                            sample(n),
                          stringsAsFactors = F)
    
    pheno.test <- pheno %>%
      mutate(names = pheno %>% pull(i)) %>% 
      inner_join(samples, by = c("names", "Participant_ID")) %>% 
      # Because dry each participant has 2 dry spots, these repetitions are made. Therefore, I will have to reme the repetitions
      .[sample(nrow(.)),] %>%
      filter(!duplicated(Participant_ID))
    
    # This, will assure that one participant contribute to one sample
    counts <- count(pheno.test, names) %>% pull(n) %>% paste0(collapse = ":")
    
    micro.r.test <- micro.r %>% 
      right_join(pheno.test %>% select(NGS_ID), by = "NGS_ID") %>% 
      column_to_rownames("NGS_ID")
    
    micro.dis <- vegdist(micro.r.test, method = "bray")
    
    # Set formula
    con <- controls
    f.cha <- paste(c(con,i), collapse = " + ") %>% 
      paste("micro.dis ~", .)
    
    f <- f.cha %>% 
      as.formula()
    
    ## Adjusted model
    res.adj <- adonis.routine(f) %>% 
      mutate(formula = f.cha) 
    
    ## Unadjusted model
    res.unadj <- adonis.routine(paste("micro.dis", "~", i) %>% 
                                  as.formula()) %>% 
      select(-term, -Df) %>% 
      magrittr::set_colnames(paste0(colnames(.),"_unadj"))
    
    
    
    res <- bind_cols(res.adj, res.unadj) %>% 
      mutate(formula = f.cha,
             nround = n.round,
             n = nrow(pheno.test),
             counts = counts) %>% 
      bind_rows(res,.)
  }
}
# Save output

paste0("beta.final.res.tsv") %>% 
  paste0(d.out, "/", .) %>% 
  write_tsv(res, .)

summ <- res %>%
  group_by(term) %>% 
  mutate(sig = if_else(p.value < q,
                       1,
                       0),
         sig_unadj = if_else(p.value_unadj < q,
                       1,
                       0)) %>% 
  summarize(significant.pc = sum(sig)*100/n.rep,
            significant.pc_unadj = sum(sig_unadj)*100/n.rep,
            R2.avg = mean(R2),
            R2.sd = sd(R2),
            R2.avg_unadj = mean(R2_unadj),
            R2.sd_unadj = sd(R2_unadj),
            n.rep = n(),
            n.avg = mean(n),
            n.sd = sd(n))
  

summ
```


# Session information

```{r}
sessionInfo()
```

