---
title: "Prepare data for ML"
author: "Lucas Moitinho-Silva"
date: "`r Sys.Date()`"
output:
   BiocStyle::html_document:
      toc: true
      df_print: paged
      self_contained: true
      code_download: true
      highlight: tango
#bibliography: mylib.bib
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
  d.out: "./"
---


# Introduction

I will prepare data for ML

# Preparations

## Set global options

```{r style, echo = T, results="asis", cache=FALSE, message = F}
# Set knit global options
library("knitr")
options(digits = 2, width = 80)
golden_ratio <- (1 + sqrt(5)) / 2
opts_chunk$set(echo = TRUE,
               tidy = FALSE,
               include = TRUE,
               fig.path = params$FIGPATH,
               dev=c("png",'pdf'),
               fig.height = 5,
               fig.width = 4 * golden_ratio,
               comment = '  ',
               dpi = 300,
               cache = FALSE)
library("rmarkdown")

# Pretty outputs
library("BiocStyle")
library("ggthemes") # add ggplot2 themes
library("ggplot2")
theme_set(theme_few(base_size = 14))

# Set seed for reproducibility
set.seed(13)

# Set output directory
d.out <- params$d.out
rm(params)
```


## Load libraries for the session

```{r}
library(magrittr)
library(tidyverse)
library(reshape2)

```

## Import data
```{r}
d.in <- "~/IKMB/projects/skin.associations/results/analysis/1.combine.microbiome/1.join.microbiome/"

microenv <- "/home/lsilva/IKMB/projects/skin.associations/scripts/data.dic/skin.microenv.tsv" %>% 
  read.delim(stringsAsFactors = F)


meta <- "meta.rds" %>% 
  paste0(d.in, "/", .) %>% 
  readRDS() %>% 
  left_join(microenv, by = "Site") 

micro.r <- "micro.r.rds" %>% 
  paste0(d.in, "/", .) %>% 
  readRDS()

tax <- "tax.rds" %>% 
  paste0(d.in, "/", .) %>% 
  readRDS()


d.out <- paste0(d.out,  "/", "aux.files")
dir.create(d.out)
```


# Use abundant genera (> 1% to avoid impact of filered ASVs and filtered genera)

## Get genera to keep
```{r}
micro <- micro.r
pheno <- meta
pheno <- pheno %>% select(NGS_ID, Site, Cohort) %>% 
  rename("Site" = "Site")
micro <- micro %>% 
  rownames_to_column("NGS_ID") %>% 
  right_join(pheno %>% select(NGS_ID), by = "NGS_ID") %>% 
  column_to_rownames("NGS_ID")

pheno.sites <- pheno %>%
  group_by(Site, Cohort) %>% 
  count(Site) %>% 
  mutate(total = n * 5000) %>% 
  select(Site, total, Cohort)

# Get number of sequences

micro.tax <- micro %>%
  rownames_to_column("NGS_ID") %>%
  # make long
  melt(value.name = "count", variable.name = "ASV") %>%
  # Get taxonomy
  left_join(tax, by = "ASV") %>%
  select(-seqs, -Kingdom) %>%
  # Get site location
  left_join(pheno, by = "NGS_ID") %>% 
  # summarize to the genus level
  group_by(Phylum, Class, Order, Family, Genus, Cohort, Site) %>% 
  summarize(count = sum(count)) %>% 
  # Get count of total sequences per site
  left_join(pheno.sites, by = c("Site", "Cohort")) %>% 
  # Make percentage
  mutate(percentage = count*100/total) %>% 
  mutate(Site = if_else(Site == "Antecubital fossa" &
                          Cohort == "KORA FF4",
                        "Antecubital fossa (K)",
                        Site)) %>% 
  mutate(Site = if_else(Site == "Antecubital fossa" &
                          Cohort == "PopGen",
                        "Antecubital fossa (P)",
                        Site)) %>% 
  # filter genus less than 1 %
  filter(percentage > 1)
genera <- micro.tax %>% ungroup %>% pull(Genus) %>% unique()
rm(micro, pheno, micro.tax)
```

## Filter tax to get ASVs to keep
```{r}
tax <- tax %>% 
  filter(Genus %in% genera)
```

# Make genus based abundance tables
```{r}
micro.r.genus <- micro.r %>%
  rownames_to_column("NGS_ID") %>% 
  select(NGS_ID, tax %>% pull(ASV)) %>% 
 melt(value.name = "count", variable.name = "ASV") %>%
  left_join(tax %>% select(Genus, ASV), by = "ASV") %>%
  # Summarize by Genus
  group_by(Genus, NGS_ID) %>% 
  summarise(count = sum(count)) %>% 
  spread(key = Genus, value = count)
```



# join

```{r}
all <- meta %>% 
  select(NGS_ID, Participant_ID, Site, Cohort, Microenvironment) %>% 
  inner_join(micro.r.genus,
             by = "NGS_ID") %>% 
  select(-NGS_ID) %>% 
  magrittr::set_colnames(make.names(colnames(.)))
```


# Save all dataset

```{r}
"all.rds" %>% 
  paste0(d.out, "/", .) %>% 
  saveRDS(all, .)
```

# Session information

```{r}
sessionInfo()
```
