---
title: "Make first panel with data description"
author: "Lucas Moitinho-Silva"
date: "`r Sys.Date()`"
output:
   BiocStyle::html_document:
      toc: true
      code: hide
      df_print: paged
      self_contained: true
      code_download: true
      highlight: tango
#bibliography: mylib.bib
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
  d.out: "./"
---


# Introduction


# Preparations

## Set global options

```{r style, echo = T, results="asis", cache=FALSE, message = F}
#v.01
# Set knit global options
library("knitr")
options(digits = 2, width = 80)
golden_ratio <- (1 + sqrt(5)) / 2
opts_chunk$set(echo = TRUE,
               tidy = FALSE,
               include = TRUE,
               fig.path = params$FIGPATH,
               dev=c("png",'pdf'),
               fig.height = 6,
               fig.width = 5 * golden_ratio,
               comment = '  ',
               dpi = 300,
               cache = FALSE)
library("rmarkdown")

# Pretty outputs
library("BiocStyle")
library("ggthemes") # add ggplot2 themes
library("ggplot2")
theme_set(theme_few(base_size = 10))

# Set seed for reproducibility
set.seed(13)
# Color
cbp1 <- c("#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999")[c(2,5,1,6,7,8)]
paired <- RColorBrewer::brewer.pal(12, "Paired")
scale_fill_discrete <- function(...) {
  scale_fill_manual(..., values = cbp1)
}
scale_colour_discrete <- function(...) {
  scale_colour_manual(..., values = cbp1)
}


# Set output directory
d.out <- params$d.out
rm(params)
```


## Load libraries for the session

```{r}
library(ggplot2)
library(tidyverse)
library(RColorBrewer)
library(reshape2)
library(vegan)
```

## Import data
```{r}

folder <- "~/IKMB/projects/skin.associations/results/analysis/1.combine.microbiome/1.join.microbiome/" 


#Read pop data
pheno <- "meta.rds" %>% 
  paste0(folder, "/", .) %>% 
  readRDS(.)
micro.r <- "micro.r.rds" %>% 
  paste0(folder, "/", .) %>% 
  readRDS(.)
tax <- "tax.rds" %>% 
  paste0(folder, "/", .) %>% 
  readRDS(.)

# Read combined diversity analysis

div.folder <- "~/IKMB/projects/skin.associations/results/analysis/1.combine.microbiome/3.plot"

beta <- "to.plot.beta.rds" %>% 
  paste0(div.folder, "/", .) %>% 
  readRDS(.)

microenv <- "~/IKMB/projects/skin.associations/scripts/data.dic/skin.microenv.tsv" %>% 
  read_tsv()

# Add roc

g.roc <- "~/IKMB/projects/skin.associations/results/analysis/1.combine.microbiome/2.predictors/g.auc.rds" %>% 
  readRDS()
```


## Convert info

```{r}
micro <- micro.r
pheno <- pheno %>% select(NGS_ID, Site, Cohort) %>% 
  rename("Site" = "Site")
micro <- micro %>% 
  rownames_to_column("NGS_ID") %>% 
  right_join(pheno %>% select(NGS_ID), by = "NGS_ID") %>% 
  column_to_rownames("NGS_ID")

pheno.sites <- pheno %>%
  group_by(Site, Cohort) %>% 
  count(Site) %>% 
  mutate(total = n * 5000) %>% 
  select(Site, total, Cohort)

# Get number of sequences

micro.tax <- micro %>%
  rownames_to_column("NGS_ID") %>%
  # make long
  melt(value.name = "count", variable.name = "ASV") %>%
  # Get taxonomy
  left_join(tax, by = "ASV") %>%
  select(-seqs, -Kingdom) %>%
  # Get site location
  left_join(pheno, by = "NGS_ID") %>% 
  # summarize to the genus level
  group_by(Phylum, Class, Order, Family, Genus, Cohort, Site) %>% 
  summarize(count = sum(count)) %>% 
  # Get count of total sequences per site
  left_join(pheno.sites, by = c("Site", "Cohort")) %>% 
  # Make percentage
  mutate(percentage = count*100/total) %>% 
  mutate(Site = if_else(Site == "Antecubital fossa" &
                          Cohort == "KORA FF4",
                        "Antecubital fossa (K)",
                        Site)) %>% 
  mutate(Site = if_else(Site == "Antecubital fossa" &
                          Cohort == "PopGen",
                        "Antecubital fossa (P)",
                        Site))
```

# Prepare to pplot
```{r}
comb <- micro.tax %>%
  filter(percentage > 0) %>% 
  #combine genera that are low abundant
  ungroup() %>%
  mutate(Genus = as.character(Genus),
         Family = as.character(Family),
         Order = as.character(Order),
         Class = as.character(Class),
         Phylum = as.character(Phylum)) %>% 
  mutate(Genus = if_else(percentage < 1,
                         "Others (< 1%)",
                         Genus),
         Family = if_else(percentage < 1,
                          "Others (< 1%)",
                          Family),
         Order = if_else(percentage < 1,
                         "Others (< 1%)",
                         Order),
         Class = if_else(percentage < 1,
                         "Others (< 1%)",
                         Class),
         Phylum = if_else(percentage < 1,
                          "Others (< 1%)",
                          Phylum)) %>%
  group_by(Phylum, Class, Order, Family, Genus, Cohort, Site) %>%
  summarize(count = sum(count), percentage = sum(percentage))
```

## Plot

```{r}
# Get colors
getPalette <- colorRampPalette(brewer.pal(8, "Dark2")[7:1])
colourCount <- comb %>%
  ungroup() %>% 
  select(Genus) %>%
  unique() %>%
  nrow()

# Get order of Genus

genera <- comb %>% 
  pull(Genus) %>% 
  unique()
genera.levels <- c(setdiff(genera, "Others (< 1%)") %>% sort(), "Others (< 1%)")

g.tax <- comb %>% 
  ungroup() %>% 
  mutate(Genus = factor(Genus, levels = genera.levels)) %>%
  #add new naming
  left_join(microenv, by = "Site") %>% 
  mutate(Site = if_else(Site == "Behind ear",
                        "Retroauricular fold",
                        Site)) %>% 
  #mutate(Site = paste0(Site, " (", str_sub(Cohort, 1,1), ")")) %>% 
  mutate(Site = factor(Site, levels = c("Dorsal forearm",
                                        "Volar forearm",
                                        "Antecubital fossa (P)",
                                        "Antecubital fossa (K)",
                                        "Forehead",
                                        "Retroauricular fold"))) %>% 
  mutate(Site = fct_rev(Site)) %>% 
  ggplot(aes(x = Site, y = percentage, fill = Genus)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = getPalette(colourCount)) +
  facet_grid(rows = vars(Microenvironment), scales = "free_y") +
  #ggpubr::rotate_x_text() +
  labs(y = "Abundance (%)") +
  guides(fill=guide_legend(ncol=1)) +
  theme(legend.position = "bottom"#,
        #axis.text.x = element_blank(), 
        #axis.ticks.x = element_blank()
        ) +
  coord_flip() +
  guides(fill=guide_legend(ncol=3))

g.tax
```




# Beta

```{r}
g.mds <- beta %>% 
  #add new naming
  left_join(microenv, by = "Site") %>% 
  mutate(Site = if_else(Site == "Behind ear",
                        "Retroauricular fold",
                        Site)) %>% 
  #mutate(Site = paste0(Site, " (", str_sub(Cohort, 1,1), ")")) %>% 
  mutate(Site = factor(Site, levels = c("Dorsal forearm",
                                        "Volar forearm",
                                        "Antecubital fossa (P)",
                                        "Antecubital fossa (K)",
                                        "Forehead",
                                        "Retroauricular fold"))) %>% 
  ggpubr::ggscatterhist(.,
  x = "MDS1", y = "MDS2",
  color = "Site",
  alpha = 0.9, # comment out this and last line to remove the split by species
  #margin.plot = "histogram", # I'd suggest removing this line to get density plots
  margin.params = list(fill = "Site", color = "darkgrey", size = 0.2),
  margin.plot = "boxplot",
  ggtheme = theme_few(),
  legend = "bottom",
  palette = cbp1)
g.mds 

```


# Add Roc plot
```{r}
g.roc
```


# Combine the plots

```{r, fig.height=6, fig.width=16}

ggpubr::ggarrange(g.tax,
                  g.roc,
                  g.mds,
                  ncol = 3,
                  labels = "AUTO",
                  widths = c(1,1,1))
```




# Session information

```{r}
sessionInfo()
```
