---
title: "Make figures kora environment"
author: "Lucas Moitinho-Silva"
date: "`r Sys.Date()`"
output:
   BiocStyle::html_document:
      toc: true
      code: hide
      df_print: paged
      self_contained: true
      code_download: true
      highlight: tango
#bibliography: mylib.bib
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
  d.out: "./"
---


# Preparations

## Set global options

```{r style, echo = T, results="asis", cache=FALSE, message = F, warning = F}
#v.01
# Set knit global options
library("knitr")
options(digits = 2, width = 80)
golden_ratio <- (1 + sqrt(5)) / 2
opts_chunk$set(echo = TRUE,
               tidy = FALSE,
               include = TRUE,
               fig.path = params$FIGPATH,
               dev=c("png",'pdf'),
               fig.height = 6,
               fig.width = 5 * golden_ratio,
               comment = '  ',
               dpi = 300,
               cache = FALSE)
library("rmarkdown")

# Pretty outputs
library("BiocStyle")
library("ggthemes") # add ggplot2 themes
library("ggplot2")
theme_set(theme_few(base_size = 14))

# Set seed for reproducibility
set.seed(13)
# Color blind friendly pallet
cbp1 <- c("#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999")

# Set output directory
d.out <- params$d.out
rm(params)
```


## Load libraries for the session

```{r}
library(ggplot2)
library(tidyverse)
library(reshape2)
library(RColorBrewer)
library(tidytext)
library(Hmisc)
library(ggnewscale)
```


## Import files
```{r}
microenv <- "~/IKMB/projects/skin.associations/scripts/data.dic/skin.microenv.tsv" %>% 
  read_tsv()

tax <- "~/IKMB/projects/skin.associations/results/analysis/1.combine.microbiome/1.join.microbiome/master.tax.rds" %>% 
  readRDS()

deseq <- "~/IKMB/projects/skin.associations/results/analysis/3.results.tables/asv.tsv" %>% 
  read_tsv() %>% 
  filter(Test.batch == "Environment")
# Import beta

beta <- "~/IKMB/projects/skin.associations/results/analysis/3.results.tables/beta.tsv"  %>% 
  read_tsv() %>% 
  filter(Test.batch == "Environment")

``` 

# Set variables
```{r}
sites <- deseq %>% 
  select(Site, Cohort) %>% 
  unique %>% 
  mutate(names = abbreviate(paste0(Site,
                                   ".",
                                   str_sub(Cohort,1,1))) %>% make.names())

weights <- deseq %>% 
  select(rel.abundance, seqs, Site) %>% 
  unique()
```

# Plot Beta

## Names
```{r}
beta <- beta %>%
  filter(Sig. == "y")
beta
```

# Process ASV

## Rename
```{r}
res <- deseq
```

## Join results

```{r}


df <- res %>%
  filter(Site == sites$Site[1]) %>% 
  select(seqs, Group, Description, log2FoldChange, lfcSE, stat, pvalue, padj) 

colnames(df) <- c("seqs", "Group", "Description", sites$names[1], 
                  paste0(sites$names[1], "_", "lfcSE"),
                  paste0(sites$names[1], "_", "stat"), 
                  paste0(sites$names[1], "_", "pvalue"),
                  paste0(sites$names[1], "_", "padj"))


for (i in 2:nrow(sites)){
  df.temp <- res %>%
    filter(Site == sites$Site[i]) %>% 
    select(seqs, Group, Description, log2FoldChange, lfcSE, stat, pvalue, padj) 
  colnames(df.temp) <- c("seqs", "Group", "Description", sites$names[i], 
                         paste0(sites$names[i], "_", "lfcSE"),
                         paste0(sites$names[i], "_", "stat"), 
                         paste0(sites$names[i], "_", "pvalue"),
                         paste0(sites$names[i], "_", "padj"))
  
  
  df <- full_join(df,
                  df.temp,
                  by = c("seqs", "Group", "Description"))
  rm(df.temp)
}

```

## Add taxonomy

```{r}
df <- df %>%
  left_join(tax %>% select(seqs, everything()), by = "seqs") 
```

## Format

```{r}
to.plot <- df %>% 
  select(sites$names, Phylum, Family, Genus, Species,seqs, ASV, Group, Description) %>% 
  melt(id.vars = c("Phylum", "Genus", "Family", "Species","seqs", "ASV", "Group", "Description")) %>% 
  mutate(value = value %>% as.numeric()) %>% 
  rename("names" = "variable") %>% 
  left_join(sites, by = "names") %>% 
  left_join(microenv, by =  "Site") %>% 
  filter((Site %in% sites$Site) & (!is.na(value))) %>% 
  mutate(Species = if_else(str_detect(Species, "(unc.)"),
                           Species,
                           paste0(Genus," ",Species))) %>%
  mutate(Species = gsub("\\(unc.\\)",  "", Species)) %>% 
  left_join(weights, by = c("Site", "seqs")) %>% 
  unique()
```

# Count associations

```{r, fig.width=14, fig.height=14}

unique.associations.site <- count(to.plot, ASV, Description) %>%
  mutate(n = as.character(n)) %>%
  count(n)
# Count associations
unique.associations.site
unique.associations.site %>% pull(nn) %>% sum

unique.associations.site %>% 
  ggplot(aes(x = n, y = nn)) +
  geom_col()


count(to.plot, ASV, Description, Site) %>% group_by(Site) %>% count()
```



# Format subgroups

```{r}
to.plot <- to.plot %>% 
  mutate(Subgroup = case_when (str_sub(Description, 1,4) == "Free" ~ "Free time\noutdoors",
                               str_sub(Description, 1,4) == "Holi" ~ "Holidays\noutdoors",
                               str_sub(Description, 1,4) == "Hour" ~ "Hours\noutdoors",
                               str_sub(Description, 1,4) == "Anim" ~ "Animal\ncontact",
                               str_sub(Description, 1,4) == "High" ~ "Education",
                               str_sub(Description, 1,4) == "Loca" ~ "Dwelling",
                               str_sub(Description, 1,4) == "Coha" ~ "Dwelling",
                               Description == "Sun protection in summer (frequency)" ~ "UV protection",
                               TRUE ~ Group), 
         Description = case_when (str_sub(Description, 1,4) == "Free" ~ str_replace(Description,"Free time outdoors - ", ""),
                                  str_sub(Description, 1,4) == "Holi" ~ str_replace(Description, "Holidays outdoors - ", ""),
                                  str_sub(Description, 1,4) == "Hour" ~ str_replace(Description, "Hours outdoors - ", ""),
                                  TRUE ~ Description)) %>% 
  mutate(Description = if_else (Description == "Sun protection in summer (frequency)",
                                "Sun protection\nin summer (freq.)",
                                Description)) %>% 
  mutate(Description = if_else (Description == "Highest vocational qualification",
                                "Highest voc. qual.",
                                Description)) %>% 
  mutate(Description = if_else (Description == "Location",
                                "Location (city:rural)",
                                Description)) %>% 
  mutate(Description = if_else (Description == "Cohabiting couple",
                                "Cohabiting couple (n:y)",
                                Description))

```

# Overview

```{r}
asvs.per.site <- to.plot %>% 
  mutate(Group = if_else(!Group %in% c("Diet", "Others"),
                         abbreviate(Group, dot = T),
                         Group)) %>% 
  mutate(Microenvironment = if_else(Microenvironment == "Sebaceous",
                                    "Seb.",
                                    Microenvironment)) %>% 
  group_by(Description, Site, Group, Microenvironment, Subgroup) %>% count()

g1.1 <- asvs.per.site %>% 
  ungroup() %>% 
  mutate(Subgroup = if_else(Subgroup == "Animal\ncontact",
                            "Animal contact",
                            Subgroup)) %>% 
  mutate(Site = str_replace(Site, " ", "\n")) %>% 
  ggplot(aes(x = Site, y = Description)) +
  geom_tile(aes(fill = n)) +
  ggpubr::rotate_x_text() +
  facet_grid(cols = vars(Microenvironment), rows = vars(Subgroup), scales = "free", space = "free") +
  labs (fill = "ASVs (n)", y = "Factor") +
  theme(legend.position = "right",
        strip.text.y.right = element_text(angle = 0, hjust = 0)) +
  scale_fill_continuous(breaks=seq(0,30,by= 5))
g1.1


asvs.per.site %>% 
  arrange(desc(n))

```

# General overview 

```{r, warning=F}
top.associations <- to.plot %>% 
  mutate(presence = 1) %>% 
  group_by(Genus, Family, Phylum, Site) %>% 
  summarise(sum = sum(presence)) %>%
  mutate(weights = 1) %>% 
  group_by(Genus, Family, Phylum) %>% 
  #get averages
  summarise(avg.per.microenvironemt = weighted.mean(sum, weights), sd.per.microenvironemt = sqrt(wtd.var(sum, weights))) %>% 
  arrange(desc(avg.per.microenvironemt)) %>% 
  ungroup() %>%
  top_n(n = 10, wt = avg.per.microenvironemt) %>% 
  mutate(Genus = factor(Genus, levels=unique(Genus))) 

g2 <- ggplot(top.associations, aes(x = Genus, y = avg.per.microenvironemt, fill = Phylum)) +
  geom_col() +
  scale_fill_brewer(palette = "Dark2") +
  ggpubr::rotate_x_text()+
  labs(y = "ASVs/\nmicroenvironment") +
  theme(legend.position = "right") +
  geom_errorbar(aes(ymin=avg.per.microenvironemt-sd.per.microenvironemt, ymax=avg.per.microenvironemt+sd.per.microenvironemt), width=.2,
                position=position_dodge(.9)) +
  guides (fill = guide_legend(ncol=1))

g2
top.associations %>% 
  mutate(avg.per.microenvironemt = round(avg.per.microenvironemt, 1),
         sd.per.microenvironemt = round(sd.per.microenvironemt,1)) 
```

# Overview by genus
```{r, warning=F}

associations <- to.plot %>% 
  mutate(presence = 1) %>% 
  group_by(Genus, Family, Phylum, Site, Group, Description) %>% 
  summarise(sum = sum(presence), value = mean(abs(value))) %>%
  mutate(weights = 1) %>% 
  group_by(Genus, Family, Phylum, Group, Description) %>% 
  #get averages
  summarise(avg.per.microenvironemt = weighted.mean(sum, weights), sd.per.microenvironemt = sqrt(wtd.var(sum, weights)),
            lfc.avg.per.microenvironemt = weighted.mean(value, weights),
            lfc.sd.per.microenvironemt = sqrt(wtd.var(value, weights)))
```
## Get maximum
```{r}
to.plot %>% filter(Genus == "Acinetobacter") %>% 
  count(Site)
```


# Select the top 3 genus
```{r}
to.plot.selected <- to.plot %>% 
  filter(Genus %in% c("Staphylococcus", "Corynebacterium", "Acinetobacter")) %>%
  mutate(Species = str_replace(Species, "Staphylococcus", "S.")) %>% 
  mutate(Species = str_replace(Species, "Corynebacterium", "C.")) %>% 
  mutate(Species = str_replace(Species, "Acinetobacter", "A.")) %>% 
  mutate(Species = paste(Species, ASV)) %>% 
  mutate(Genus = abbreviate(Genus, dot = T)) %>% 
  mutate(Subgroup =  if_else (Subgroup == "UV protection",
                              "UV prot.",
                              Subgroup))

```

# Pets and outdoors

```{r, fig.width=16, fig.height=10}
this.plot <- to.plot.selected %>% 
  filter((Group == "Pets" &
         Subgroup == "Pets")|
           (Subgroup == "Holidays\noutdoors" )|
          (Subgroup == "Free time\noutdoors") ) %>% 
  mutate(Subgroup = factor(Subgroup, levels = c("Pets", "Free time\noutdoors", "Holidays\noutdoors" )),
         Description = factor(Description, levels = c("Cat", "Dog","Rodent", "Other","Beach / lake",  "Green spaces", "Mountain region", "Urban spaces"))) %>% 
  mutate(Site = str_replace_all(Site, " ", "\n"))

g3 <- ggplot(this.plot,
               aes(x = value, y = Species, label = Species)) +
  geom_vline(xintercept = 0, color="grey") +
  facet_grid(cols = vars(Subgroup),rows = vars(Genus), scales = "free", space = "free_y") +
  labs(size = "Abun. (%)", x = "log2 fold change", y  = "ASVs") +
  #scale_color_manual(values = pal.ori[1:4]) +
  scale_size_continuous(breaks=seq(0,max(this.plot$rel.abundance),by = 4)) +
  geom_point(aes(size = rel.abundance,
                 color = Description,
                 shape = Site
  ), alpha = 0.7) +
  theme(legend.position = "bottom") +
  guides(size=guide_legend(ncol=1), color = guide_legend(ncol=1),fill = guide_legend(ncol=1), shape = guide_legend(ncol=1)) +
  labs(color = "Factor")
g3
```

# Final figure
```{r, fig.width= 14, fig.height=10}
g12 <- ggpubr::ggarrange(#g1,
  g1.1, g2, labels = "AUTO",  nrow = 2, heights =  c(1.8,1))

g.final <- ggpubr::ggarrange(g12, g3, labels = c("", "C"), ncol = 2, widths  = c(1,1.5))
g.final
```


# Supplementary figure

```{r, fig.width=15, fig.height=11}
this.plot <- to.plot.selected %>% 
  filter(!((Group == "Pets" &
         Subgroup == "Pets")|
           (Subgroup == "Holidays\noutdoors" )|
          (Subgroup == "Free time\noutdoors")))


ggplot(this.plot,
               aes(x = value, y = Species, label = Species)) +
  geom_vline(xintercept = 0, color="grey") +
  facet_grid(cols = vars(Subgroup),rows = vars(Genus), scales = "free", space = "free_y") +
  labs(size = "Abun. (%)", x = "log2 fold change", y  = "ASVs") +
  scale_size_continuous(breaks=seq(0,max(this.plot$rel.abundance),by= 1)) +
  ggpubr::rotate_x_text(angle = 45) +
  # Environment
  geom_point(data = this.plot %>% 
               filter(Subgroup == "UV prot."),
             aes(color = Description, 
                 size = rel.abundance,
                 shape = Site
             ), alpha = 0.7) +
  labs(color = "UV protection") +
  new_scale("color") +
  
  # Hours outdoors
   # Environment
  geom_point(data = this.plot %>% 
               filter(Subgroup == "Hours\noutdoors"),
             aes(color = Description, 
                 size = rel.abundance,
                 shape = Site
             ), alpha = 0.7) +
  labs(color = "Hours\noutdoors") +
  new_scale("color") +
  # Education
  geom_point(data = this.plot %>% 
               filter(Subgroup == "Education"),
             aes(size = rel.abundance,
                 color = Description,
                 shape = Site
             ), alpha = 0.7) +
  labs(color = "Education") +
  new_scale("color") +
  # Dwelling
  geom_point(data = this.plot %>% 
               filter(Subgroup == "Dwelling"),
             aes(size = rel.abundance,
                 color = Description,
                 shape = Site
             ), alpha = 0.7) +
  labs(color = "Dwelling") +
  new_scale("color") +
  # Pet contact intensity
  geom_point(data = this.plot %>% 
               filter(Subgroup == "Animal\ncontact"),
             aes(size = rel.abundance,
                 color = Description,
                 shape = Site
             ), alpha = 0.7) +
  labs(color = "Animal contact") +
  new_scale("color") +
  theme(legend.position = "right") +
  guides(size=guide_legend(ncol=2), color = guide_legend(ncol=1),fill = guide_legend(ncol=1), shape = guide_legend(ncol=1)) 

```





```{r}
sessionInfo()
```
