---
title: "Make figures for kora host traits"
author: "Lucas Moitinho-Silva"
date: "`r Sys.Date()`"
output:
   BiocStyle::html_document:
      toc: true
      code: hide
      df_print: paged
      self_contained: true
      code_download: true
      highlight: tango
#bibliography: mylib.bib
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
  d.out: "./"
---

# Preparations

## Set global options

```{r style, echo = T, results="asis", cache=FALSE, message = F}
#v.01
# Set knit global options
library("knitr")
options(digits = 2, width = 80)
golden_ratio <- (1 + sqrt(5)) / 2
opts_chunk$set(echo = TRUE,
               tidy = FALSE,
               include = TRUE,
               fig.path = params$FIGPATH,
               dev=c("png",'pdf'),
               fig.height = 6,
               fig.width = 5 * golden_ratio,
               comment = '  ',
               dpi = 300,
               cache = FALSE)
library("rmarkdown")

# Pretty outputs
library("BiocStyle")
library("ggthemes") # add ggplot2 themes
library("ggplot2")
theme_set(theme_few(base_size = 16))

# Set seed for reproducibility
set.seed(13)
# Color blind friendly pallet
cbp1 <- c("#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999")[c(2,5,1,6,7,8)]

# scale_fill_discrete <- function(...) {
#    scale_fill_manual(..., values = cbp1)
# }
# scale_colour_discrete <- function(...) {
#   scale_colour_manual(..., values = cbp1)
# }

# Set output directory
d.out <- params$d.out
rm(params)
```


## Load libraries for the session

```{r}
library(ggplot2)
library(tidyverse)
library(reshape2)
library(RColorBrewer)
library(tidytext)
library(Hmisc) # For weighted wtd.var
```




## Import files
```{r}
microenv <- "~/IKMB/projects/skin.associations/scripts/data.dic/skin.microenv.tsv" %>% 
  read_tsv()

tax <- "~/IKMB/projects/skin.associations/results/analysis/1.combine.microbiome/1.join.microbiome/master.tax.rds" %>% 
  readRDS()

deseq <- "~/IKMB/projects/skin.associations/results/analysis/3.results.tables/asv.tsv" %>% 
  read_tsv() %>% 
  filter(Test.batch == "Age/BMI/Sex/Lifestyle") %>% 
  filter(Cohort == "KORA FF4")
# Import beta

beta <- "~/IKMB/projects/skin.associations/results/analysis/3.results.tables/beta.tsv"  %>% 
  read_tsv() %>% 
  filter(Test.batch == "Age/BMI/Sex/Lifestyle") %>% 
  filter(Cohort == "KORA FF4")

beta.micro.env <- "~/IKMB/projects/skin.associations/results/kora/2.host.trait.set/5.test.sites/beta.final.res.tsv" %>% 
  read_tsv()

``` 

# Set variables
```{r}
pal <- c("#E69F00", "#56B4E9", "#009E73",
         "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999")[c(2,5,1,6,7,8)][c(4,6)]

sites <- deseq %>% 
  select(Site, Cohort) %>% 
  unique %>% 
  mutate(names = abbreviate(paste0(Site,
                                   ".",
                                   str_sub(Cohort,1,1))) %>% make.names())

weights <- deseq %>% 
  select(rel.abundance, seqs, Site) %>% 
  unique()
```

# Prepare test sites

```{r}
q <-0.05
n.rep <- 100
beta.micro.env <- beta.micro.env %>% 
  group_by(term) %>% 
  mutate(sig = if_else(p.value < q,
                       1,
                       0)) %>% 
  summarise(significant.pc = sum(sig)*100/n.rep,
            R2.avg = mean(R2),
            R2.sd = sd(R2),
            n.rep = n(),
            n.avg = mean(n),
            n.sd = sd(n)) %>% 
  filter(term == "Microenvironment") %>% 
  ungroup() %>% 
  mutate(term = gsub("Microenvironment", "Micro-\nenvironment", term))

g.micro.env <- ggplot(beta.micro.env, aes(term, R2.avg*100)) +
  geom_col() +
  labs(y = "Variation\nexplained (%)", x =  "") +
  coord_flip() + 
  geom_errorbar(aes(ymin = R2.avg*100 - R2.sd*100, 
                    ymax = R2.avg*100 + R2.sd*100), 
                width=.2,
                position=position_dodge(.9)) +
  theme(axis.text = element_text(size = 16), legend.text = element_text(size = 16))
g.micro.env

beta.micro.env
```

# Plot Beta

## Names
```{r}
beta <- beta %>%
  filter(Sig. == "y") %>% 
  mutate(Site = Site %>%
           as.character() %>% 
           gsub("Retroauricular", "R.", .) %>% 
           gsub("Antecubital", "A.", .)) 
beta
```

## Plot
```{r}
g1 <- ggplot(beta, aes(x = Description, y = R2*100, group = Site)) +
  geom_bar(stat="identity", width=.5, position = "dodge", aes(fill = Site)) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  facet_grid(rows = vars(Group), scales = "free", space = "free") +
  theme(legend.position = "bottom",axis.text = element_text(size = 16), legend.text = element_text(size = 16)) +
  guides(fill=guide_legend(ncol=1))  +
  labs(x = "Factor", y = "Variation\nexplained (%)")
g1  
```

# Process ASV

```{r}
res <- deseq %>% 
  filter(padj < 0.05)
```

## Join results

```{r}


df <- res %>%
  filter(Site == sites$Site[1]) %>% 
  select(seqs, Group, Description, log2FoldChange, lfcSE, stat, pvalue, padj) 

colnames(df) <- c("seqs", "Group", "Description", sites$names[1], 
                  paste0(sites$names[1], "_", "lfcSE"),
                  paste0(sites$names[1], "_", "stat"), 
                  paste0(sites$names[1], "_", "pvalue"),
                  paste0(sites$names[1], "_", "padj"))


for (i in 2:nrow(sites)){
  df.temp <- res %>%
    filter(Site == sites$Site[i]) %>% 
    select(seqs, Group, Description, log2FoldChange, lfcSE, stat, pvalue, padj) 
  colnames(df.temp) <- c("seqs", "Group", "Description", sites$names[i], 
                         paste0(sites$names[i], "_", "lfcSE"),
                         paste0(sites$names[i], "_", "stat"), 
                         paste0(sites$names[i], "_", "pvalue"),
                         paste0(sites$names[i], "_", "padj"))
  
  
  df <- full_join(df,
                  df.temp,
                  by = c("seqs", "Group", "Description"))
  rm(df.temp)
}

```

## Add taxonomy

```{r}
df <- df %>%
  left_join(tax %>% select(seqs, everything()), by = "seqs") 
```

## Format


```{r}
p <- df %>% 
  select(sites$names, Phylum, Family, Genus, Species,seqs, ASV, Group, Description) %>% 
  melt(id.vars = c("Phylum", "Genus", "Family", "Species","seqs", "ASV", "Group", "Description")) %>% 
  mutate(value = value %>% as.numeric())

se <- df %>% 
  select(paste0(sites$names, "_lfcSE"), Phylum, Family, Genus, Species,seqs, ASV, Group, Description) %>% 
  melt(id.vars = c("Phylum", "Genus", "Family", "Species","seqs", "ASV", "Group", "Description")) %>% 
  rename(se = value) %>% 
  mutate(se = se %>% as.numeric()) %>% 
  mutate(variable = str_replace(variable, "_lfcSE", ""))

to.plot <- full_join(p,se, by = c("Phylum", "Genus", "Family", "Species", "seqs", "ASV", "Group", "Description", "variable"))  %>%
  rename("names" = "variable") %>% 
  left_join(sites, by = "names") %>% 
  left_join(microenv, by =  "Site") %>% 
  filter((Site %in% sites$Site) & (!is.na(value))) %>% 
  mutate(Species = if_else(str_detect(Species, "(unc.)"),
                           Species,
                           paste0(Genus," ",Species))) %>%
  mutate(Species = gsub("\\(unc.\\)",  "", Species)) %>% 
  left_join(weights, by = c("Site", "seqs")) %>% 
  unique()
```

# Count associations
```{r, fig.width=14, fig.height=14}

unique.associations.site <- count(to.plot, ASV, Description) %>%
  mutate(n = as.character(n)) %>%
  count(n)
# Count associations
unique.associations.site
unique.associations.site %>% pull(nn) %>% sum

unique.associations.site %>% 
  ggplot(aes(x = n, y = nn)) +
  geom_col()
```

# Overview

```{r, warning=F}
asvs.per.site <- to.plot %>%  mutate(Site = Site %>%
                                       as.character() %>% 
                                       gsub("Retroauricular", "R.", .) %>% 
                                       gsub("Antecubital", "A.", .)) %>% 
  mutate(Group = if_else(Group == "Health parameters",
                         "Antibiotics",
                         Group)) %>% 
  mutate(Group = if_else(!Group %in% c("Diet", "Others"),
                         gsub(" ", "\n", Group),
                         Group)) %>% 
  mutate(Microenvironment = if_else(Microenvironment == "Sebaceous",
                                    "Seb.",
                                    Microenvironment)) %>% 
  group_by(Description, Site, Group, Microenvironment) %>%
  count() %>% 
  mutate(Description = if_else(Description == "Antibiotics (<6-8w)",
                               "Antibiotics (<8w)",
                               Description)) %>% 
    mutate(Group = if_else(!Group %in%  c("Age/BMI/Sex", "Diet"),
                               "Others",
                               Group))

g1.1 <- asvs.per.site %>% 
  ggplot(aes(x = Site, y = Description)) +
  geom_tile(aes(fill = n)) +
  ggpubr::rotate_x_text() +
  facet_grid(cols = vars(Microenvironment), rows = vars(Group), scales = "free", space = "free") +
  labs (fill = "ASVs (n)", y = "Factor") +
  theme(legend.position = "right", strip.text.x = element_text(angle = 90, size = 16), panel.spacing = unit(0.0, "lines"), strip.text.y = element_text(angle = 0, size = 16, hjust = 0),
        axis.text = element_text(size = 16), text = element_text(size = 16)) +
  scale_fill_continuous(breaks=seq(0,30,by= 5))
g1.1


asvs.per.site %>% 
  arrange(desc(n))

```

# General overview 

```{r, warning=F}
top.associations <- to.plot %>% 
  # Get cumulated relative abundance of affected avs in each site 
  ungroup() %>% 
  select(-Group, -Description, -value, -se) %>% 
  unique() %>% 
  group_by(Genus, Family, Phylum, Site) %>% 
  summarise(sum = sum(rel.abundance), n = n()) %>%
  # Get average by microenvironment
  mutate(weights = 1) %>% 
  group_by(Genus, Family, Phylum) %>% 
  #get averages
  summarise(avg.abund = weighted.mean(sum, weights, na.rm = T), sd.abund = sqrt(wtd.var(sum, weights, na.rm = T)),
            avg.n = weighted.mean(n, weights, na.rm = T), sd.n = sqrt(wtd.var(n, weights, na.rm = T))) %>% 
  arrange(desc(avg.abund)) %>% 
  ungroup() %>%
  top_n(n = 10, wt = avg.abund) %>% 
  mutate(Genus = factor(Genus, levels=unique(Genus)))
top.associations[is.na(top.associations)] <-0

g2 <- ggplot(top.associations, aes(x = avg.abund, y = avg.n, label = Genus)) +
  geom_errorbar(aes(xmin=avg.abund-sd.abund, xmax=avg.abund+sd.abund), width=0,
                position=position_dodge(.9), alpha = 0.3) +
  geom_errorbar(aes(ymin=avg.n-sd.n, ymax=avg.n+sd.n), width=0,
                position=position_dodge(.9), alpha = 0.3) +
  geom_point(aes(color = Phylum), size = 3) +
  scale_x_log10() +
  scale_y_log10() +
  scale_fill_brewer(palette = "Dark2") +
  labs(x = "Total abundance (%)" , y = "Associated ASVs (n)") +
  ggrepel::geom_text_repel(size = 6, box.padding = 1) +
  theme(legend.position = "right",
        legend.text = element_text(size = 16),
        text = element_text(size = 16)) +
  guides (color = guide_legend(ncol=1))  +
  scale_colour_brewer(palette = "Dark2")


g2
top.associations
```

# Overview by genus
```{r, warning=F}

associations <- to.plot %>% 
  mutate(presence = 1) %>% 
  group_by(Genus, Family, Phylum, Site, Group, Description) %>% 
  summarise(sum = sum(presence), value = mean(abs(value))) %>%
  mutate(weights = if_else(Site %in% c("Volar forearm",
                                       "Dorsal forearm"),
                           0.5,
                           1)) %>% 
  group_by(Genus, Family, Phylum, Group, Description) %>% 
  #get averages
  summarise(avg.per.microenvironemt = weighted.mean(sum, weights), sd.per.microenvironemt = sqrt(wtd.var(sum, weights)),
            lfc.avg.per.microenvironemt = weighted.mean(value, weights),
            lfc.sd.per.microenvironemt = sqrt(wtd.var(value, weights)))
```

# Plot overview
```{r, fig.width= 9, fig.height=9}
g1.micro <- ggpubr::ggarrange(g.micro.env, g1, labels = "AUTO", nrow = 2, heights = c(1,3))
g12 <- ggpubr::ggarrange(g1.micro, g1.1, labels = c("", "C"),  ncol = 2, widths = c(1.5,3))
g12
ggpubr::ggarrange(g12, g2, labels = c("", "D"),  nrow = 2, heights = c(1.5,1.2))
```

# Session information
```{r}
sessionInfo()
```
