---
title: "Make figures for PopGen host traits "
author: "Lucas Moitinho-Silva"
date: "`r Sys.Date()`"
output:
   BiocStyle::html_document:
      toc: true
      code: hide
      df_print: paged
      self_contained: true
      code_download: true
      highlight: tango
#bibliography: mylib.bib
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
  d.out: "./"
---

# Preparations

## Set global options

```{r style, echo = T, results="asis", cache=FALSE, message = F}
#v.01
# Set knit global options
library("knitr")
options(digits = 2, width = 80)
golden_ratio <- (1 + sqrt(5)) / 2
opts_chunk$set(echo = TRUE,
               tidy = FALSE,
               include = TRUE,
               fig.path = params$FIGPATH,
               dev=c("png",'pdf'),
               fig.height = 6,
               fig.width = 5 * golden_ratio,
               comment = '  ',
               dpi = 300,
               cache = FALSE)
library("rmarkdown")

# Pretty outputs
library("BiocStyle")
library("ggthemes") # add ggplot2 themes
library("ggplot2")
original <- theme_get()
theme_set(theme_few(base_size = 14))

# Set seed for reproducibility
set.seed(13)
# Color blind friendly pallet



# Set output directory
d.out <- params$d.out
rm(params)
```


## Load libraries for the session

```{r}
library(ggplot2)
library(tidyverse)
library(reshape2)
library(RColorBrewer)
library(tidytext)
library(Hmisc) # For weighted wtd.var
```

```{r}
microenv <- "~/IKMB/projects/skin.associations/scripts/data.dic/skin.microenv.tsv" %>% 
  read_tsv()

tax <- "~/IKMB/projects/skin.associations/results/analysis/1.combine.microbiome/1.join.microbiome/master.tax.rds" %>% 
  readRDS()

deseq <- "~/IKMB/projects/skin.associations/results/analysis/3.results.tables/asv.tsv" %>% 
  read_tsv() %>% 
  filter(Test.batch == "Age/BMI/Sex/Lifestyle") %>% 
  filter(Cohort == "PopGen")
# Import beta

beta <- "~/IKMB/projects/skin.associations/results/analysis/3.results.tables/beta.tsv"  %>% 
  read_tsv() %>% 
  filter(Test.batch == "Age/BMI/Sex/Lifestyle") %>% 
  filter(Cohort == "PopGen")

beta.micro.env <- "~/IKMB/projects/skin.associations/results/popgen/2.host.trait.set/5.test.sites/beta.final.res.tsv" %>% 
  read_tsv()
``` 

# Set variables

```{r}
pal <- c("#E69F00", "#56B4E9", "#009E73",
         "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999")[c(2,5,1,6,7,8)][c(1,2,3,5)]

order.col <- c("Dorsal forearm",
               "Volar forearm",
               "Antecubital fossa",
               "Forehead")
sites <- deseq %>% 
  select(Site, Cohort) %>% 
  unique %>% 
  mutate(names = abbreviate(paste0(Site,
                                   ".",
                                   str_sub(Cohort,1,1))) %>% make.names())


weights <- deseq %>% 
  select(rel.abundance, seqs, Site) %>% 
  unique()
```


# Prepare test sites

```{r}
q <-0.05
n.rep <- 100
beta.micro.env <- beta.micro.env %>% 
  group_by(term) %>% 
  mutate(sig = if_else(p.value < q,
                       1,
                       0)) %>% 
  summarise(significant.pc = sum(sig)*100/n.rep,
            R2.avg = mean(R2),
            R2.sd = sd(R2),
            n.rep = n(),
            n.avg = mean(n),
            n.sd = sd(n)) %>% 
  filter(term == "Microenvironment")

beta.micro.env 

```

# Plot Beta

## Names
```{r}
beta <- beta %>%
  filter(Cohort == "PopGen") %>% 
  filter(Sig. == "y") %>% 
  mutate(Site = factor(Site,
                       levels = order.col))
beta
```

## Plot
```{r}
g1 <- ggplot(beta, aes(x = Description, y = R2, group = Site)) +
  geom_bar(stat="identity", width=.5, position = "dodge", aes(fill = Site)) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  facet_grid(rows = vars(Group), scales = "free", space = "free") +
  theme(legend.position = "bottom") +
  guides(fill=guide_legend(ncol=1)) +
  labs(x = "Factor", y = "Effect size (R2)")
g1  
```


# Proess ASV

```{r}
res <- deseq %>% 
  filter(padj < 0.05)
```

## Join results

```{r}
sites <- res %>% 
  select(Site, Cohort) %>% 
  unique %>% 
  mutate(names = abbreviate(paste0(Site,
                                   ".",
                                   str_sub(Cohort,1,1))) %>% make.names())

weights <- res %>% 
  select(rel.abundance, seqs, Site) %>% 
  unique()

df <- res %>%
  filter(Site == sites$Site[1]) %>% 
  select(seqs, Group, Description, log2FoldChange, lfcSE, stat, pvalue, padj) 

colnames(df) <- c("seqs", "Group", "Description", sites$names[1], 
                  paste0(sites$names[1], "_", "lfcSE"),
                  paste0(sites$names[1], "_", "stat"), 
                  paste0(sites$names[1], "_", "pvalue"),
                  paste0(sites$names[1], "_", "padj"))


for (i in 2:nrow(sites)){
  df.temp <- res %>%
    filter(Site == sites$Site[i]) %>% 
    select(seqs, Group, Description, log2FoldChange, lfcSE, stat, pvalue, padj) 
  colnames(df.temp) <- c("seqs", "Group", "Description", sites$names[i], 
                         paste0(sites$names[i], "_", "lfcSE"),
                         paste0(sites$names[i], "_", "stat"), 
                         paste0(sites$names[i], "_", "pvalue"),
                         paste0(sites$names[i], "_", "padj"))
  
  
  df <- full_join(df,
                  df.temp,
                  by = c("seqs", "Group", "Description"))
  rm(df.temp)
}

```

## Add taxonomy

```{r}
df <- df %>%
  left_join(tax %>% select(seqs, everything()), by = "seqs")
```

## Format

```{r}
p <- df %>% 
  select(sites$names, Phylum, Family, Genus, Species,seqs, ASV, Group, Description) %>% 
  melt(id.vars = c("Phylum", "Genus", "Family", "Species","seqs", "ASV", "Group", "Description")) %>% 
  mutate(value = value %>% as.numeric())

se <- df %>% 
  select(paste0(sites$names, "_lfcSE"), Phylum, Family, Genus, Species,seqs, ASV, Group, Description) %>% 
  melt(id.vars = c("Phylum", "Genus", "Family", "Species","seqs", "ASV", "Group", "Description")) %>% 
  rename(se = value) %>% 
  mutate(se = se %>% as.numeric()) %>% 
  mutate(variable = str_replace(variable, "_lfcSE", ""))

to.plot <- full_join(p,se, by = c("Phylum", "Genus", "Family", "Species", "seqs", "ASV", "Group", "Description", "variable"))  %>%
  rename("names" = "variable") %>% 
  left_join(sites, by = "names") %>% 
  left_join(microenv, by =  "Site") %>% 
  filter((Site %in% sites$Site) & (!is.na(value))) %>% 
  mutate(Species = if_else(str_detect(Species, "(unc.)"),
                           Species,
                           paste0(Genus," ",Species))) %>%
  mutate(Species = gsub("\\(unc.\\)",  "", Species)) %>% 
  left_join(weights, by = c("Site", "seqs")) %>% 
  unique() %>% 
  mutate(Site = factor(Site,
                       levels = order.col))
```

# Count associations

```{r, fig.width=14, fig.height=14}

unique.associations.site <- count(to.plot, ASV, Description) %>%
  mutate(n = as.character(n)) %>%
  count(n)
# Count associations
unique.associations.site
unique.associations.site %>% pull(nn) %>% sum

unique.associations.site %>% 
  ggplot(aes(x = n, y = nn)) +
  geom_col()

```


# Select asvs to consider

```{r}
to.consider <- count(to.plot, ASV, Description) %>% 
  filter(n > 1) %>% 
  select(-n)

to.plot <- to.plot %>% 
  right_join(to.consider, by = c("ASV", "Description"))
```


# Overview

```{r, warning=F}
asvs.per.site <- to.plot %>% 
  mutate(Group = if_else(!Group %in% c("Diet", "Others", "Age/BMI/Sex"),
                         abbreviate(Group, dot = T),
                         Group)) %>% 
  mutate(Microenvironment = if_else(Microenvironment == "Sebaceous",
                                    "Seb.",
                                    Microenvironment)) %>% 
  group_by(Description, Site, Group, Microenvironment) %>% count()

g1.1 <- asvs.per.site %>% 
  ggplot(aes(x = Site, y = Description)) +
  geom_tile(aes(fill = n)) +
  ggpubr::rotate_x_text() +
  facet_grid(cols = vars(Microenvironment), rows = vars(Group), scales = "free", space = "free") +
  labs (fill = "Diversity\n(n of ASVs)", y = "Factor") +
  theme(legend.position = "right") +
  scale_fill_continuous(breaks=seq(0,30,by= 5))
g1.1


asvs.per.site %>% 
  arrange(desc(n))

```

# General overview 

```{r}
top.associations <- to.plot %>% 
  # Get cumulated relative abundance of affected avs in each site 
  ungroup() %>% 
  select(-Group, -Description, -value, -se) %>% 
  unique() %>% 
  group_by(Genus, Family, Phylum, Site) %>% 
  summarise(sum = sum(rel.abundance), n = n()) %>%
  # Get average by microenvironment
  mutate(weights = if_else(Site %in% c("Volar forearm",
                                       "Dorsal forearm"),
                           0.5,
                           1)) %>% 
  group_by(Genus, Family, Phylum) %>% 
  #get averages
  summarise(avg.abund = weighted.mean(sum, weights, na.rm = T), sd.abund = sqrt(wtd.var(sum, weights, na.rm = T)),
            avg.n = weighted.mean(n, weights, na.rm = T), sd.n = sqrt(wtd.var(n, weights, na.rm = T))) %>% 
  arrange(desc(avg.abund)) %>% 
  ungroup() %>%
  top_n(n = 10, wt = avg.abund) %>% 
  mutate(Genus = factor(Genus, levels=unique(Genus))) 


g2 <- ggplot(top.associations, aes(x = avg.abund, y = avg.n, label = Genus)) +
  geom_errorbar(aes(xmin=avg.abund-sd.abund, xmax=avg.abund+sd.abund), width=0,
                position=position_dodge(.9), alpha = 0.3) +
  geom_errorbar(aes(ymin=avg.n-sd.n, ymax=avg.n+sd.n), width=0,
                position=position_dodge(.9), alpha = 0.3) +
  geom_point(aes(color = Phylum), size = 3) +
  scale_x_log10() +
  scale_y_log10() +
  scale_fill_brewer(palette = "Dark2") +
  labs(x = "Total abundance (%)" , y = "Diversity (n of ASVs)") +
  ggrepel::geom_text_repel() +
  theme(legend.position = "bottom") +
  guides (color = guide_legend(ncol=2))  +
  scale_colour_brewer(palette = "Dark2")


g2
top.associations
```

# Overview by genus
```{r, warning=F}

associations <- to.plot %>% 
  mutate(presence = 1) %>% 
  group_by(Genus, Family, Phylum, Site, Group, Description) %>% 
  summarise(sum = sum(presence), value = mean(abs(value))) %>%
  mutate(weights = if_else(Site %in% c("Volar forearm",
                                       "Dorsal forearm"),
                           0.5,
                           1)) %>% 
  group_by(Genus, Family, Phylum, Group, Description) %>% 
  #get averages
  summarise(avg.abund = weighted.mean(sum, weights), sd.abund = sqrt(wtd.var(sum, weights)),
            lfc.avg.abund = weighted.mean(value, weights),
            lfc.sd.abund = sqrt(wtd.var(value, weights)))
```

# Plot overview figure

```{r, fig.width= 16, fig.height=7}

g12 <- ggpubr::ggarrange(g1, g1.1, g2, labels = c("A", "B", "C"),  ncol = 3, widths =  c(0.5,0.75,0.75))
g12
```

# Plot ASVs

```{r, fig.width=16, fig.height=14}
theme_set(original)
#Prepare data to all plots
to.plot.selected <- to.plot %>% 
  filter(Genus %in% c("Staphylococcus", "Corynebacterium", "Propionibacterium")) %>%
  mutate(Species = if_else(str_detect(Species, " $"),
                           "Unclassified",
                           Species)) %>%
  #mutate(Species = paste(Species, ASV)) %>% 
  mutate(Genus = abbreviate(Genus, dot = T)) %>% 
  mutate(Site = factor(Site, levels = c("Dorsal forearm", "Volar forearm" ,
                                        "Antecubital fossa",
                                        "Forehead")))
# get asv codes per species

asv = to.plot.selected %>% 
  ungroup() %>% 
  select(Genus, Species, ASV) %>% 
  unique() %>% 
  group_by(Genus, Species) %>% 
  mutate(ASV.code = 1:n() %>% 
           as.character()) %>%
  ungroup() %>% 
  select(ASV, ASV.code)

#a dd to the df
to.plot.selected <- left_join(to.plot.selected, asv, by = "ASV")


# Select data to plot
this.plot <- to.plot.selected %>%
  filter(Group %in% c("Age/BMI/Sex")) %>% 
  mutate(Description = if_else(Description == "Sex",
                               "Sex (m:f)",
                               Description)) 
labels = this.plot$ASV

empty = c()
for (i in 1:length(labels)){
  value = labels[i]
  if(!is.na(value)){
    if(!(value %in% empty)){
  empty = c(empty, value)}else{labels[i] = NA}}
}
this.plot$labels = labels

g3.1 <- ggplot(this.plot,
       aes(x = value, y = Species, label = ASV)) +
  ggrepel::geom_label_repel(data = this.plot %>% filter(!is.na(labels)), box.padding = 1, aes(color = ASV.code)) +
  geom_vline(xintercept = 0, color="lightgray", linetype = 2) +
  geom_jitter(aes(color = ASV.code, 
                  size = rel.abundance,
                  shape = Site), alpha = 0.8, width = 0, height = 0.05) +
  facet_grid(cols = vars(Description),rows = vars(Genus), scales = "free", space = "free_y") +
  labs(size = "Abun. (%)", x = "Effect size (Log2FC)", y  = "Species") +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "darkgrey"),
        panel.grid.major = element_blank(),
        panel.grid.major.y =  element_line(colour = "lightgray", linetype = 3),
        text = element_text(size = 14),
        panel.border = element_rect(colour = "darkgray", fill=NA)) +
  guides(size = guide_legend(ncol = 1), color = FALSE) +
  scale_size_continuous(breaks=seq(0,max(this.plot$rel.abundance),by= 10)) +
  ggpubr::rotate_x_text(angle = 45) +
  scale_colour_brewer(palette = "Dark2")

  

# Select data to plot
this.plot <- to.plot.selected %>%
  filter(Group %in% c("Diet"))

labels = this.plot$ASV

empty = c()
for (i in 1:length(labels)){
  value = labels[i]
  if(!is.na(value)){
    if(!(value %in% empty)){
  empty = c(empty, value)}else{labels[i] = NA}}
}
this.plot$labels = labels

g3.2 <- ggplot(this.plot,
       aes(x = value, y = Species, label = ASV)) +
  ggrepel::geom_label_repel(data = this.plot %>% filter(!is.na(labels)), box.padding = 1, aes(color = ASV.code)) +
  geom_vline(xintercept = 0, color="lightgray", linetype = 2) +
  geom_jitter(aes(color = ASV.code, 
                  size = rel.abundance,
                  shape = Site), alpha = 0.8, width = 0, height = 0.05) +
  facet_grid(cols = vars(Description),rows = vars(Genus), scales = "free", space = "free_y") +
  labs(size = "Abun. (%)", x = "Effect size (Log2FC)", y  = "Species") +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "darkgrey"),
        panel.grid.major = element_blank(),
        panel.grid.major.y =  element_line(colour = "lightgray", linetype = 3),
        text = element_text(size = 14),
        panel.border = element_rect(colour = "darkgray", fill=NA)) +
  guides(size = guide_legend(ncol = 1), color = FALSE) +
  scale_size_continuous(breaks=seq(0,max(this.plot$rel.abundance),by= 1)) +
  ggpubr::rotate_x_text(angle = 45)  +
  scale_colour_brewer(palette = "Dark2")


ggpubr::ggarrange(g3.1, g3.2, labels = "AUTO", nrow = 2, heights = c(10, 7))
```

# Plot ASVs complement
```{r, fig.width=14, fig.height=6}

this.plot <- to.plot.selected %>%
  filter(!Group %in% c("Age/BMI/Sex", "Diet")) %>% 
  mutate(Description = if_else(Description == "Sport in summer (h/week)",
                               "Sport in summer\n(h/week)",
                               Description)) %>% 
  mutate(Description = if_else(Description == "Regular sports",
                               "Regular sports",
                               Description)) %>% 
  mutate(Description = if_else(Description == "Lotion/cream (<24h)",
                               "Lotion/\ncream (<24h)",
                               Description)) %>% 
  mutate(Description = if_else(Description == "Wash (<24h)",
                               "Wash (<24h)",
                               Description)) %>% 
  mutate(Description = if_else(Description == "Smoking",
                               "Smoking\n(smoker:non-)",
                               Description))
labels = this.plot$ASV

empty = c()
for (i in 1:length(labels)){
  value = labels[i]
  if(!is.na(value)){
    if(!(value %in% empty)){
  empty = c(empty, value)}else{labels[i] = NA}}
}
this.plot$labels = labels

g3.3 <- ggplot(this.plot,
       aes(x = value, y = Species, label = ASV)) +
  ggrepel::geom_label_repel(data = this.plot %>% filter(!is.na(labels)), box.padding = 1, aes(color = ASV.code)) +
  geom_vline(xintercept = 0, color="lightgray", linetype = 2) +
  geom_jitter(aes(color = ASV.code, 
                  size = rel.abundance,
                  shape = Site), alpha = 0.8, width = 0, height = 0.05) +
  facet_grid(cols = vars(Description),rows = vars(Genus), scales = "free", space = "free_y") +
  labs(size = "Abun. (%)", x = "Effect size (Log2FC)", y  = "Species") +
  theme(panel.background = element_blank(),
        axis.line = element_line(colour = "darkgrey"),
        panel.grid.major = element_blank(),
        panel.grid.major.y =  element_line(colour = "lightgray", linetype = 3),
        text = element_text(size = 14),
        panel.border = element_rect(colour = "darkgray", fill=NA)) +
  guides(size = guide_legend(ncol = 1), color = FALSE) +
  scale_size_continuous(breaks=seq(0,max(this.plot$rel.abundance),by= 5)) +
  ggpubr::rotate_x_text(angle = 45)  +
  scale_colour_brewer(palette = "Dark2")
g3.3
```

# Session information
```{r}
sessionInfo()
```
