---
title: "Plot sharedness"
author: "Lucas Moitinho-Silva"
date: "`r Sys.Date()`"
output:
   BiocStyle::html_document:
      toc: true
      code: hide
      df_print: paged
      self_contained: true
      code_download: true
      highlight: tango
#bibliography: mylib.bib
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
  d.out: "./"
---


# Introduction

The files were pre-calculated by Nicole.

# Preparations

## Set global options

```{r style, echo = T, results="asis", cache=FALSE, message = F}
#v.01
# Set knit global options
library("knitr")
options(digits = 2, width = 80)
golden_ratio <- (1 + sqrt(5)) / 2
opts_chunk$set(echo = TRUE,
               tidy = FALSE,
               include = TRUE,
               fig.path = params$FIGPATH,
               dev=c("png",'pdf'),
               fig.height = 6,
               fig.width = 5 * golden_ratio,
               comment = '  ',
               dpi = 300,
               cache = FALSE)
library("rmarkdown")

# Pretty outputs
library("BiocStyle")
library("ggthemes") # add ggplot2 themes
library("ggplot2")
theme_set(theme_few(base_size = 14))

# Set seed for reproducibility
set.seed(13)
# Color blind friendly pallet
cbp1 <- c("#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999")

scale_fill_discrete <- function(...) {
   scale_fill_manual(..., values = cbp1)
}
scale_colour_discrete <- function(...) {
  scale_colour_manual(..., values = cbp1)
}

# Set output directory
d.out <- params$d.out
rm(params)
```


## Load libraries for the session

```{r}
library(ggplot2)
library(tidyverse)
library(reshape2)
```

## Import data
```{r}
load("~/IKMB/projects/skin.associations/nicole.analysis/radial_plot_kora_popgen_data.RData")

data <- data %>% 
  mutate(group = factor(group, levels = c("Dosal \n forearm",
                                          "Volar \n forearm",
                                          "Antecubital \n fossa (P)",
                                          "Antecubital \n fossa (K)",
                                          "Forehead",
                                          "Retroauricular \n fold")))

label_data <- label_data %>% 
  mutate(group = factor(group, levels = c("Dosal \n forearm",
                                          "Volar \n forearm",
                                          "Antecubital \n fossa (P)",
                                          "Antecubital \n fossa (K)",
                                          "Forehead",
                                          "Retroauricular \n fold")))


```

#Plot

```{r}
p <- ggplot(data %>% filter(!is.na(site)), aes(x=site, y=value, fill=group)) +       # Note that id is a factor. If x is numeric, there is some space between the first bar
  
  geom_bar(aes(x=site, y=value, fill=group), stat="identity", alpha =0.9) +

  ggpubr::rotate_x_text() +
  facet_wrap(~group, scales = "free") +
  scale_fill_manual("legend", values = c("Retroauricular \n fold" = pal.ori[6],
                                         "Antecubital \n fossa (K)" = pal.ori[4],
                                         "Antecubital \n fossa (P)" = pal.ori[3],
                                         "Volar \n forearm" =pal.ori[2] ,
                                         "Dosal \n forearm" = pal.ori[1],
                                       "Forehead" = pal.ori[5] )) +
  ylim(0, 100) +
  labs(x = "Compared site", y = "Sequences shared (%)") +
  theme (legend.position = "none")

p

saveRDS(p, paste0(d.out, "/", "shared.rds"))

```



# Conclusion

# Session information

```{r}
sessionInfo()
```
